"""article templates table

Revision ID: b263392b2f34
Revises: 1a683c01cf1b
Create Date: 2026-09-15 17:33:30.511425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b263392b2f34'
down_revision = '1a683c01cf1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_templates_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_templates_key'))

    op.drop_table('article_templates')
    # ### end Alembic commands ###
