"""company accounts table

Revision ID: beb4059efc00
Revises: cde50b613f0a
Create Date: 2026-09-16 14:18:53.722916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb4059efc00'
down_revision = 'cde50b613f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('volume', sa.String(length=120), nullable=True),
    sa.Column('billing', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('owner_email', sa.String(length=200), nullable=True),
    sa.Column('work_email', sa.String(length=200), nullable=True),
    sa.Column('lead', sa.JSON(), nullable=True),
    sa.Column('quote', sa.JSON(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('account_activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_accounts_owner_user_id'), ['owner_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_accounts_owner_user_id'))

    op.drop_table('company_accounts')
    # ### end Alembic commands ###
