"""articles table with category link

Revision ID: cde50b613f0a
Revises: 1f073164e108
Create Date: 2026-09-16 11:11:17.551293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde50b613f0a'
down_revision = '1f073164e108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('editor', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('tone', sa.String(length=30), nullable=True),
    sa.Column('access_label', sa.String(length=120), nullable=True),
    sa.Column('read_time', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('category_label', sa.String(length=200), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('public_access_date', sa.String(length=50), nullable=True),
    sa.Column('publish_date', sa.String(length=50), nullable=True),
    sa.Column('publish_time', sa.String(length=50), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_category_id'), ['category_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_category_id'))

    op.drop_table('articles')
    # ### end Alembic commands ###
